name: Build and Deploy HTML

on:
  push:
    tags:
      - "v*"

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    env:
      ANY_APPS_HOME_REPO: ${{ secrets.ANY_APPS_HOME_REPO }}
      ANY_APPS_HOME_TOKEN: ${{ secrets.ANY_APPS_HOME_TOKEN }}
      PROJECT_NAME: world-clock
      BRANCH_NAME: ${{ github.ref_name }}
      ANY_APPS_REPO: /tmp/any-apps

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Install dependencies and build
        run: |
          echo "It should run something to build"

      - name: Set git configuration
        run: |
          git config --global user.name "${PROJECT_NAME} github-actions[bot]"
          git config --global user.email "${PROJECT_NAME} github-actions[bot]@users.noreply.github.com"

      - name: Clone home repo
        run: |
          rm -rf ${ANY_APPS_REPO}
          mkdir -p ${ANY_APPS_REPO}
          git clone https://x-access-token:${ANY_APPS_HOME_TOKEN}@github.com/${ANY_APPS_HOME_REPO}.git ${ANY_APPS_REPO}

      - name: Copy build directory to tmp directory
        run: |
          mkdir -p /tmp/${PROJECT_NAME}
          cp -rvf public/* /tmp/${PROJECT_NAME}

      - name: Push build to target repo
        working-directory: ${{ env.ANY_APPS_REPO }}
        continue-on-error: true
        run: |
          git checkout -b ${BRANCH_NAME}
          git reset --hard ${BRANCH_NAME}
          rm -rfv public/${PROJECT_NAME}
          mv -fv /tmp/${PROJECT_NAME} public/
          git add public/${PROJECT_NAME}
          git commit -m "DEPLOY ${BRANCH_NAME} via action"
          git push origin --force ${BRANCH_NAME}

      - name: create pull request
        # working-directory: ${{ env.ANY_APPS_REPO }}
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.ANY_APPS_HOME_TOKEN }}
          branch: ${{ github.ref_name }}
          base: main
          title: "Release ${{ github.ref_name }}"
          body: "Automated PR for tag ${{ github.ref_name }}"
        # run: |
        #   gh pr create -B main -H ${BRANCH_NAME} --title "Deploy ${BRANCH_NAME}" --body 'Automated PR to deploy html'
        # env:
        #   GITHUB_TOKEN: ${{ secrets.ANY_APPS_HOME_TOKEN }}

          #- name: Create pull request
          #  uses: peter-evans/create-pull-request@v5
          #  with:
          #    token: ${{ secrets.ANY_APPS_HOME_TOKEN }}
          #    path: ${{ env.ANY_APPS_REPO }}
          #    title: "Deploy ${PROJECT_NAME} ${{ github.run_id }}"
          #    body: "Automated PR to deploy HTML content"
          #    branch: ${{ env.PROJECT_NAME }}
          #    base: main