name: Build and Deploy HTML

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Install dependencies and build
        run: |
          echo "It should run something to build"

      - name: Push build to target repo
        env:
          TARGET_REPO: ${{ secrets.ANY_APPS_HOME_REPO }}
          TARGET_BRANCH: main
          TOKEN: ${{ secrets.ANY_APPS_HOME_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          mkdir any-apps
          mv public any-apps/world-clock
          cd any-apps/world-clock

          git init
          git remote add origin https://x-access-token:${TOKEN}@github.com/${TARGET_REPO}.git
          git checkout -b ${TARGET_BRANCH}
          mkdir world-clock

          git add .
          git commit -m "DEPLOY WORLD CLOCK"
          git push --force origin ${TARGET_BRANCH}
